spring:
  profiles:
    active: dev
---
spring:
  datasource:
    hikari:
      maximumPoolSize: 60
      minimum-idle: 10
      jdbc-url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MariaDB103Dialect

  jwt:
    secret: qwerqwerqwerqwerqwerqwerqweqwrqweqwrqwr

  jackson:
    serialization:
      fail-on-empty-beans: false

  config:
    activate:
      on-profile: dev

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
#        type:
#          trace
---
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      jdbc-url: jdbc:h2:mem:test
      maximumPoolSize: 10

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect

  jwt:
    secret: qwerqwerqwerqwerqwerqwerqweqwrqweqwrqwr

  jackson:
    serialization:
      fail-on-empty-beans: false
  config:
    activate:
      on-profile: test