spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#          dialect: org.hibernate.dialect.MariaDB103Dialect

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: qwerqwerqwerqwerqwerqwerqweqwrqweqwrqwr

  imp:
    key: 9365280131116708
    secret: tkeVqQRndtYrkYBH9JROrSDVG2NnTZBmkPiKF97TD6kX5WFeFw27pG26JPuCP5Y9VhTAr1u48P1dLGsq
    api-url: https://api.iamport.kr

  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
      force-request: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          trace
---
spring:
  datasource:
    hikari:
      maximumPoolSize: 60
      minimum-idle: 10
      jdbc-url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa

  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      maximumPoolSize: 60
      minimum-idle: 10
      jdbc-url: jdbc:mariadb://main-mariadb.ca2o8h2fpksq.ap-northeast-2.rds.amazonaws.com:3306/copang
      driver-class-name: org.mariadb.jdbc.Driver
      username: copang
      password: copangmaster
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MariaDB103Dialect
    generate-ddl: true

---
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      jdbc-url: jdbc:h2:mem:test
      maximumPoolSize: 10

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect

  jwt:
    secret: qwerqwerqwerqwerqwerqwerqweqwrqweqwrqwr

  jackson:
    serialization:
      fail-on-empty-beans: false
  config:
    activate:
      on-profile: test
#server:
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#      force-response: true
#      force-request: true