= Copang API Guide
monk;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: 에제 요청
:operation-http-request-title: 에제 요청
:operation-http-response-title: 에제 응답
:operation-request-fields-title: 요청 data
:operation-response-fields-title: 응답 data
:operation-response-fields-data-title: 응답 데이터 필드


[[Introduction]]
== 소개

[[overview]]
== Overview

[[overview_http_verbs]]
=== HTTP verbs

NOTE: HTTP 메서드 안내



|===
| Verb | Usage

| `GET`
| 리소스 요청

| `POST`
| 새로운 리소스 생성

| `PATCH`
| 일부 정보 업데이트

| `PUT`
| 정보 업데이트

| `DELETE`
| 삭제요청


|===

[[overview_http_status_codes]]
=== HTTP status codes

HTTP 상태코드 안내

|===
| Status code | Usage

| `200 OK`
|  요청 성공
The request completed successfully

| `201 Created`
| 성공적으로 리소스가 만들어졌을때

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
|
잘못된 요청시

| `405 Method Not Allowed`
| URI 에서 메소드를 지원하지 않을때

| `404 Not Found`
| The requested resource did not exist
| `403 Forbidden`
| 로그인은 했지만 권한이 없는 리소스에 접근시

| `401 UnAuthorized`
| 인증 실패시 EX) 로그인 실패
|===

[[overvie_error]]
=== 에러 메세지 안내

==== 엑세스 권한이 없을때

operation::auth/auth-failed[snippets='response-body,response-fields']

[[Authentication]]
=== 인증정보가 포함된 요청

Authorization 헤더에 Bearer Scheme으로 토큰을 넣어주시면 됩니다
Bearer 띄우고 token

operation::auth/with-auth[snippets='http-request,request-headers']

[[authentication]]
= Auth

== Login 로그인 요청
==== `POST` /api/auth/login

operation::auth/login[snippets='http-request,http-response,request-fields,response-fields']

== SignUp 회원가입 요청
==== `POST` /api/auth/signup

operation::auth/signup-client[snippets='http-request,http-response,request-fields,response-fields']


== 회원 탈퇴
==== `DELETE` /api/user

operation::c

[[client]]
= Client 유저 서비스

[[]]
== 유저 정보 가져오기
==== `GET` /api/user


operation::client/get-one-user[snippets='http-request,http-response,request-headers']



===== `GET` /api/user/list


operation::client/get-user-list[snippets='http-request,request-headers,http-response,response-fields']

== 유저 업데이트

operation::client/update[snippets='http-request,request-headers,http-response,response-fields']



[[Orders]]
= 주문 API

== 주문 하기
==== `POST` /api/orders

operation::orders/start-order[snippets='http-request,request-fields,request-headers,http-response,response-fields']

== 주문 진행시키기
==== `PATCH` /api/orders/:orderId/proceed

operation::orders/proceed-order[snippets='request-headers,path-parameters,http-request,http-response,response-fields']

== 주문 단건 조회
==== `GET` /api/order/:orderId

operation::orders/get-one-order[snippets='request-headers,path-parameters,http-request,http-response,response-fields']

== 유저 주문 조회하기
==== `GET` /api/order/client

operation::orders/get-client-order-list[snippets='request-headers,http-request,http-response,response-fields']


= 장바구니 API

== 장바구니 조회 [유저 기준]
==== `GET` /api/cart

operation::cart/get-client-cart[snippets='http-request,request-headers,http-response,response-fields']

== 장바구니 아이템추가
==== `POST` /api/cart/item

기존에 존재하는 아이템에 추가시 수량이 추가됩니다


operation::cart/add-cart-item[snippets='http-request,request-headers,request-fields,http-response,response-fields']

== 장바구니 아이템 수량 업데이트
==== `POST` /api/cart/item/amount


operation::cart/update-cart-item-amount[snippets='http-request,request-headers,request-fields,http-response,response-fields']


== 장바구니 아이템 빼기
==== `DELETE` /api/cart/item/:itemDetailId

operation::cart/delete-item[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

== 장바구니 비우기
==== `DELETE` /api/cart

operation::cart/clear-cart[snippets='http-request,request-headers,http-response,response-fields']



= 주소 API

== 주소등록
==== `POST` /api/address

처음 등록한 주소가 기본주소가 됩니다

operation::address/create[snippets='http-request,request-headers,request-fields,http-response,response-fields']

== 주소 조회 [유저 기준]
==== `GET` /api/address

operation::address/get-all-address[snippets='http-request,request-headers,http-response,response-fields']

== 주소 삭제
==== `DELETE` /api/address/:addressid

operation::address/delete-address[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

== 기본주소지 설정
==== `PATCH` /api/address/:addressid

operation::address/set-default[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

== 기본주소지로 저장하기
==== `POST` /api/address/default

operation::address/save-default[snippets='http-request,request-headers,request-fields,http-response,response-fields']

== 주소지 수정하기
==== `PUT` /api/address/:addressid

수정하실 필드만 채워서 보내시면 됩니다

operation::address/update-address[snippets='http-request,request-headers,request-fields,http-response,response-fields']



[[resources_tag]]
= 상품 정보 APIs

== 상품 목록
==== `GET` /api/item/list

상품중에 대표로 선택된 옵션들만 출력됩니다, 현재는 첫번째가 대표로 선택됩니다

operation::item/get-mainlist[snippets='http-request,http-response,response-fields']

== 상품 상세 목록
==== `GET` /api/item/list/itemid=:itemId
operation::item/get-itemlist[snippets='http-request,path-parameters,http-response,response-fields']


== 상품 리스트 등록
==== `POST` /api/item/add

상품 새로 등록

operation::item/post-save[snippets='http-request,request-fields,http-response,response-fields']

== 상품 옵션 추가
==== `POST` /api/item/detail
operation::item/post-save-detail[snippets='http-request,request-fields,http-response,response-fields']


== 상품 삭제
==== `DELETE` /api/item/delete/:itemId

상품 삭제시 등록된 모든 상품옵션은 삭제됩니다

operation::item/delete-item[snippets='http-request,path-parameters,http-response,response-fields']

== 상품 옵션 삭제
==== `GET` /api/item/delete/item-detail=:itemDetailId
operation::item/delete-itemDetail[snippets='http-request,path-parameters,http-response,response-fields']

== 상품 옵션 단일 수정
==== `PUST` /api/item/update

상품 이름과 설명도 수정 가능합니다

operation::item/put-update[snippets='http-request,request-fields,http-response,response-fields']

== 상품 다중 수정
==== `PUT` /api/item/update/list
operation::item/put-update-list[snippets='http-request,request-fields,http-response,response-fields']


[[review]]
= Review API

== 리뷰등록
==== `POST` /api/review/register

operation::review/post[snippets='http-request,request-headers,request-fields,http-response,response-fields,response-fields-data']


== 리뷰 가져오기 [유저기준]
==== `GET` /api/review/user

operation::review/user[snippets='http-request,request-headers,http-response']
operation::review/post[snippets='response-fields,response-fields-data']

== 리뷰 수정하기
==== `POST` /api/review/:reviewId

수정하실 필드만 보내시면 됩니다

operation::review/update-review[snippets='http-request,request-headers,request-fields,http-response']
operation::review/post[snippets='response-fields,response-fields-data']

== 리뷰 가져오기 [상품 기준]
==== `GET` /api/review/:itemId


= 문의 API

== 문의 등록하기
==== `POST` /api/inquiry

operation::inquiry/register-inquiry[snippets='http-request,request-headers,request-fields,http-response,response-fields,response-fields-data']

== 답변 등록하기
==== `POST` /api/:inquiryId/reply


operation::inquiry/register-reply[snippets='http-request,request-headers,path-parameters,request-fields,http-response,response-fields,response-fields-data']]

== 문의 조회

=== 유저기준
==== `GET` /api/inquiry/client

=== 판매자기준
==== `GET` /api/inquiry/seller

=== 사


