= Copang API Guide
monk;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: 에제 요청
:operation-http-request-title: 에제 요청
:operation-http-response-title: 에제 응답
:operation-request-fields-title: 요청 data
:operation-response-fields-title: 응답 data


[[Introduction]]
== 소개

[[overview]]
== Overview

[[overview_http_verbs]]
=== HTTP verbs

NOTE: HTTP 메서드 안내



|===
| Verb | Usage

| `GET`
| 리소스 요청

| `POST`
| 새로운 리소스 생성

| `PATCH`
| 일부 정보 업데이트

| `PUT`
| 정보 업데이트

| `DELETE`
| 삭제요청


|===

[[overview_http_status_codes]]
=== HTTP status codes

HTTP 상태코드 안내

|===
| Status code | Usage

| `200 OK`
|  요청 성공
The request completed successfully

| `201 Created`
| 성공적으로 리소스가 만들어졌을때

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
|
잘못된 요청시

| `405 Method Not Allowed`
| URI 에서 메소드를 지원하지 않을때

| `404 Not Found`
| The requested resource did not exist
| `403 Forbidden`
| 로그인은 했지만 권한이 없는 리소스에 접근시

| `401 UnAuthorized`
| 인증 실패시 EX) 로그인 실패
|===

[[overvie_error]]
=== 에러 메세지 안내

==== 엑세스 권한이 없을때

operation::auth/auth-failed[snippets='response-body,response-fields']

[[Authentication]]
=== 인증정보가 포함된 요청

Authorization 헤더에 Bearer Scheme으로 토큰을 넣어주시면 됩니다
Bearer 띄우고 token

operation::auth/with-auth[snippets='http-request,request-headers']

[[authentication]]
= Auth

== Login 로그인 요청

operation::auth/login[snippets='http-request,http-response,request-fields,response-fields']

== SignUp 회원가입 요청
operation::auth/signup-client[snippets='http-request,http-response,request-fields,response-fields']



[[client]]
= Client 유저 서비스

[[]]
== 유저 정보 가져오기

A `GET` request is used to access the index

operation::client/get-one-user[snippets='http-request,http-response,path-parameters,request-headers']



`GET`


operation::client/get-user-list[snippets='http-request,request-headers,http-response,response-fields']

== 유저 업데이트

operation::client/update[snippets='http-request,request-headers,http-response,response-fields']



[[Orders]]
= 주문 API

== 주문 하기
==== `POST` /api/orders

operation::orders/start-order[snippets='http-request,request-fields,request-headers,http-response,response-fields']

== 주문 진행시키기
==== `PATCH` /api/orders/:orderId/proceed

operation::orders/proceed-order[snippets='request-headers,path-parameters,http-request,http-response,response-fields']

== 주문 단건 조회
==== `GET` /api/order/:orderId

operation::orders/get-one-order[snippets='request-headers,path-parameters,http-request,http-response,response-fields']

== 유저 주문 조회하기
==== `GET` /api/order/client/:clientId

operation::orders/get-client-order-list[snippets='request-headers,path-parameters,http-request,http-response,response-fields']


= 장바구니 API

== 장바구니 조회 [유저 기준]
==== `GET` /api/cart

operation::cart/get-client-cart[snippets='http-request,request-headers,http-response,response-fields']

== 장바구니 아이템추가
==== `POST` /api/cart/item

기존에 존재하는 아이템 업데이트시 수량이 추가됩니다


operation::cart/add-cart-item[snippets='http-request,request-headers,request-fields,http-response,response-fields']

== 장바구니 아이템 수량 업데이트
==== `POST` /api/cart/item/amount


operation::cart/update-cart-item-amount[snippets='http-request,request-headers,request-fields,http-response,response-fields']


== 장바구니 아이템 빼기
==== `DELETE` /api/cart/item/:itemDetailId

operation::cart/delete-item[snippets='http-request,path-parameters,request-headers,http-response,response-fields']

== 장바구니 비우기
==== `DELETE` /api/cart

operation::cart/clear-cart[snippets='http-request,request-headers,http-response,response-fields']

[[resources_tag]]
= 상품 정보 APIs

== 상품 목록
==== `GET` /api/item/list
operation::item/get-mainlist[snippets='http-request,http-response']

== 상품 상세 목록
operation::item/get-itemlist[snippets='http-request,path-parameters,http-response']


== 상품 등록
==== `POST` /api/item
operation::item/post-save[snippets='http-request,request-fields,http-response,response-fields']



== 상품 옵션 삭제


== 상품 옵션 삭제
//==== `GET` /item/delete/itemDetail/:itemDetailId
//operation::item/delete-item[snippets='http-response,response-fields']

아직 문서화 되지 않았습니정
